{
 "title": "Grafana",
 "description": "Visualize Grafana graphs based on Gatling benchmark results stored in Influxdb. Fully compatible with Docker.",
 "time": { "from": "2022-02-14T18:19:50.034Z", "to": "2022-02-14T18:22:43.787Z" },
 "panels": [
  {
   "title": "Response times(95% Line)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    },
    {
     "alias": "users",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT mean(\"active\") FROM \"gatling.users\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "max",
     "query": "SELECT max(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='ok' group by time(1s)"
    },
    {
     "alias": "mean",
     "query": "SELECT mean(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='ok' group by time(1s)"
    },
    {
     "alias": "failed",
     "query": "SELECT max(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='ko' group by time(1s)"
    },
    {
     "alias": "users",
     "query": "SELECT mean(\"active\") FROM \"gatling.users\" WHERE $timeFilter GROUP BY time(1s) fill(null)"
    }
   ]
  },
  {
   "title": "RPS by Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='all' group by request\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "All req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" != 'allRequests' AND \"status\"='all' group by time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "All Passes",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ok') group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "All Errors",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ko') group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "Pass $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ok') group by request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Error $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND (\"request\" != 'allRequests' AND \"status\" = 'ko') group by request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (99% Line)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles99\" FROM \"gatling\" WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Latencies: Percentiles & Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "percentiles50",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles50\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "percentiles95",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles95\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "percentiles99",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles99\") FROM \"gatling\" WHERE (\"request\" != 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  }
 ]
}